title = "hadjilucasL's blog posts"
description = "The sharings of a gallus domesticus ğŸ”"

base_url = "https://www.gallus-domesticus.com/blog"
build_search_index = false
compile_sass = true
default_language = "en"
generate_rss = true
highlight_code = true
highlight_theme = "monokai"
theme = "after-dark"
taxonomies = [
    {name = "categories", rss = true },
    {name = "tags", rss = true },
]

[extra]
after_dark_menu = [
    {name = "Blog", url = "$BASE_URL/"},
    {name = "Code", url = "https://github.com/hadjilucasL"},
    {name = "Home", url = "https://www.gallus-domesticus.com"},
]
after_dark_title = "The sharings of a gallus domesticus ğŸ”"
